```yaml
name: Update Project Impact Badges

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  push:
    branches:
      - main
    paths:
      - 'project_metrics.json'

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Verify GITHUB_TOKEN
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "Error: GITHUB_TOKEN is not set"
            exit 1
          fi

      - name: Verify files exist
        run: |
          if [ ! -f project_metrics.json ]; then
            echo "Error: project_metrics.json not found"
            exit 1
          fi
          if [ ! -f README.md ]; then
            echo "Error: README.md not found"
            exit 1
          fi
          if [ ! -f .github/scripts/update_badges.py ]; then
            echo "Error: update_badges.py not found"
            exit 1
          fi
          if [ ! -r project_metrics.json ]; then
            echo "Error: project_metrics.json is not readable"
            exit 1
          fi

      - name: Debug project_metrics.json
        run: |
          echo "Contents of project_metrics.json:"
          cat project_metrics.json || echo "Error: Failed to read project_metrics.json"
          echo "File size of project_metrics.json:"
          ls -l project_metrics.json || echo "Error: Failed to get file size"

      - name: Update badges
        run: |
          python .github/scripts/update_badges.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code README.md || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "chore: update project impact badges"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```